### PR TITLE
Add static site generator

### PR DESCRIPTION
**Pull request by ioncorimenia**
This is beneficial for those with slow devices, or JavaScript disabled. Though the generated static file is a bit large (3mb), it takes very well to being gzipped (300kb).

Edit: The Travis builds seem to have failed because it cloned hax0kartik:master, instead of my pull request.

### CODE REVIEW

**Comment by hax0kartik** [comment]
Looks good! Thnx for this.

**Comment by hax0kartik** [comment]
Ok I think something is worng. Shouldn't I be able to access this using?https://hax0kartik.github.io/3dsdb/static.html
yet its giving me a 404

**Comment by ioncorimenia** [comment]
GH pages always lags behind the repo a bit, try refreshing a few times.
screenshot

**Comment by hax0kartik** [comment]
Could you confirm that `https://hax0kartik.github.io/3dsdb/static.html` is the link you are visiting and I didn't mess up things?
I'm still getting 404

**Comment by ioncorimenia** [comment]
Try clearing your cache or using a different browser. I can see the page on my end.
screenshot

**Comment by hax0kartik** [comment]
Curl seems to work, chrome and edge don't seem to. Most likely an issue on my side.

**Comment by hax0kartik** [comment]
Um my phone's browser gives 404 too :/

**Comment by ioncorimenia** [comment]
I can also see the page if I use a remote site screenshotting tool like png2web. Try visiting the site using a proxy or Tor.

**Comment by hax0kartik** [comment]
Ah Works now! Many thnx for your help! Also I might add pagination tomorrow, so you will have to do this again :p

**Pull request merged**
